### ISSUE TITLE
EGA Data Transfer task list

### ISSUE THREAD

**Issue by hknahal** [icgc-argo/ega-file-transfer#2]
EGA Data transfer tasks:

- [x] Sync data transfer

Compile lists of files to delete at EGA for:
- [x] PACA-CA
- [x] LUSC-KR

Compile data to stage at EGA for:
- [x] THCA-SA
- [x] ESAD-UK: Filter data in initial EGA/ICGC audit report to ensure files belonging to renamed donor/specimen IDs are not included. 

- [x] Contact EGA and notify them of data to stage and delete
